export * from './Company'
export * from './Feedback'
export * from './Footer'
export * from './Header'
export * from './MainSlider'
export * from './Navbar'
export * from './NotFound'
export * from './Promotion'
