import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "@/widgets/Header";
import { Navbar } from "@/widgets/Navbar";

import styles from "./layout.module.scss";
import "@/shared/styles/globals.scss";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={roboto.variable}>
      <body>
        <Header />
        <Navbar />

        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
