import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Footer, Header, Navbar } from "@/widgets/Layout";
import { getVariables } from "@/shared/api";

import styles from "./layout.module.scss";
import "@/shared/styles/globals.scss";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const variables = await getVariables();

  return (
    <html lang="ru" className={roboto.variable}>
      <body>
        <Header variables={variables} />
        <Navbar />

        <main className={styles.main}>{children}</main>
        <Footer variables={variables} />
      </body>
    </html>
  );
}
